using System;
using System.IO;
using System.Collections.Generic;
using Spectre.Console;
using Spectre.Console.Cli;
using PackageSmith.App.Bridges;
using PackageSmith.Data.State;
using PackageSmith.Data.Types;
using PackageSmith.Core.Logic;

namespace PackageSmith.App.Commands;

public sealed class NewCommand : Command<NewCommand.Settings>
{
	public sealed class Settings : CommandSettings
	{
		[CommandArgument(0, "[name]")]
		public string? PackageName { get; init; }

		[CommandOption("-d|--display")]
		public string? DisplayName { get; init; }

		[CommandOption("-o|--output")]
		public string? OutputPath { get; init; }

		[CommandOption("-t|--template")]
		public string? TemplateName { get; init; }

		[CommandOption("-l|--link")]
		public bool LinkToUnity { get; init; }

		[CommandOption("--desc|--description")]
		public string? Description { get; init; }

		[CommandOption("--author")]
		public string? AuthorName { get; init; }

		[CommandOption("--unity")]
		public string? UnityVersion { get; init; }
	}

	public override int Execute(CommandContext context, Settings settings)
	{
		string? selectedTemplate = settings.TemplateName;

		// 1. If template not specified via flag, ask user interactively
		if (string.IsNullOrEmpty(selectedTemplate))
		{
			var templates = GetAvailableTemplates();
			
			// If we have templates, give the user a choice
			if (templates.Count > 0)
			{
				var choices = new List<string> { "Standard (Empty)" };
				choices.AddRange(templates);

				var selection = AnsiConsole.Prompt(
					new SelectionPrompt<string>()
						.Title("[bold]Select a template:[/]")
						.PageSize(10)
						.AddChoices(choices));

				if (selection != "Standard (Empty)")
				{
					selectedTemplate = selection;
				}
			}
		}

		// 2. Route based on selection
		if (!string.IsNullOrEmpty(selectedTemplate) && 
		    !selectedTemplate.Equals("standard", StringComparison.OrdinalIgnoreCase) &&
		    !selectedTemplate.Equals("empty", StringComparison.OrdinalIgnoreCase) &&
		    !selectedTemplate.Equals("none", StringComparison.OrdinalIgnoreCase))
		{
			return CreateFromTemplate(settings, selectedTemplate);
		}

		return CreateStandard(settings);
	}

	private int CreateFromTemplate(Settings settings, string templateName)
	{
		AnsiConsole.MarkupLine($"[dim]Using template: [cyan]{templateName}[/][/]\n");

		var packageName = settings.PackageName ?? AnsiConsole.Ask<string>("[dim]Package name[/] (e.g. [cyan]com.studio.tool[/]):");
		var outputPath = settings.OutputPath ?? ".";

		// Get git config for defaults
		GitLogic.TryGetGitConfig(out var gitName, out var _);
		var defaultAuthor = !string.IsNullOrEmpty(gitName) ? gitName : "YourCompany";
		var defaultDisplay = !string.IsNullOrEmpty(settings.DisplayName) ? settings.DisplayName : GetDisplayNameFromPackage(packageName);

		// Prompt for additional information if not provided via CLI
		AnsiConsole.MarkupLine("[bold]Package Information[/]\n");
		var displayName = settings.DisplayName ?? AnsiConsole.Ask<string>("[dim]Display name[/]:", defaultDisplay);
		var description = settings.Description ?? AnsiConsole.Ask<string>("[dim]Description[/]:", $"Generated by {displayName}");
		var authorName = settings.AuthorName ?? AnsiConsole.Ask<string>("[dim]Author/Company name[/]:", defaultAuthor);
		var unityVersion = settings.UnityVersion ?? AnsiConsole.Ask<string>("[dim]Unity version[/]:", "2022.3");

		var templatesDir = GetAppDataPath();
		var templatePath = Path.Combine(templatesDir, "PackageSmith", "Templates", templateName);

		if (!Directory.Exists(templatePath))
		{
			AnsiConsole.MarkupLine($"[red]Error:[/] Template '[cyan]{templateName}[/]' not found.");
			AnsiConsole.MarkupLine($"[dim]Expected path:[/] {templatePath}");
			AnsiConsole.MarkupLine("\n[dim]Available templates:[/]");
			ListTemplates();
			return 1;
		}

		var fullOutputPath = Path.Combine(outputPath, packageName);

		if (!TemplateGeneratorLogic.TryGenerateFromTemplate(templatePath, fullOutputPath, packageName, displayName, description, authorName, unityVersion, out var fileCount))
		{
			AnsiConsole.MarkupLine("[red]Error:[/] Failed to generate from template");
			return 1;
		}

		AnsiConsole.MarkupLine($"[green]Success:[/] Created {fileCount} files from '[cyan]{templateName}[/]'");
		AnsiConsole.MarkupLine($"[dim]Location:[/] {fullOutputPath}");

		GitLogic.TryInitGit(fullOutputPath, out var gitSuccess);
		if (gitSuccess) AnsiConsole.MarkupLine("[dim]Git initialized[/]");

		if (settings.LinkToUnity)
		{
			if (UnityLinkLogic.TryFindUnityProject(fullOutputPath, out var unityPath))
			{
				if (UnityLinkLogic.TryLinkToUnityProject(unityPath, fullOutputPath, packageName))
				{
					AnsiConsole.MarkupLine($"[green]Linked:[/] Added to Unity project at {unityPath}");
				}
				else
				{
					AnsiConsole.MarkupLine("[yellow]Warning:[/] Failed to link to Unity project");
				}
			}
			else
			{
				AnsiConsole.MarkupLine("[yellow]Warning:[/] No Unity project found in parent directories");
			}
		}

		return 0;
	}

	private List<string> GetAvailableTemplates()
	{
		var results = new List<string>();
		var templatesDir = GetAppDataPath();
		var templatesPath = Path.Combine(templatesDir, "PackageSmith", "Templates");

		if (Directory.Exists(templatesPath))
		{
			foreach (var t in Directory.GetDirectories(templatesPath))
			{
				results.Add(Path.GetFileName(t));
			}
		}
		return results;
	}

	private int CreateStandard(Settings settings)
	{
		AnsiConsole.MarkupLine("[dim]Creating new Unity package...[/]");

		var bridge = new PackageBridge();

		var package = new PackageState
		{
			PackageName = settings.PackageName ?? "com.company.newpackage",
			DisplayName = settings.DisplayName ?? "New Package",
			Description = "A new Unity package",
			OutputPath = settings.OutputPath ?? ".",
			CompanyName = "YourCompany",
			UnityVersion = "2022.3",
			SelectedModules = PackageModuleType.Runtime | PackageModuleType.Editor,
			EcsPreset = new EcsPresetState { EnableEntities = false },
			SubAssemblies = SubAssemblyType.None,
			EnableSubAssemblies = false,
			DependencyCount = 0,
			SelectedTemplate = TemplateType.None
		};

		if (!bridge.TryCreate(in package))
		{
			AnsiConsole.MarkupLine("[red]Error:[/] Failed to create package");
			return 1;
		}

		PackageLogic.CombinePath(package.OutputPath, package.PackageName, out var fullPath);
		GitLogic.TryInitGit(fullPath, out var gitSuccess);

		AnsiConsole.MarkupLine($"[green]Success:[/] Package created");
		if (gitSuccess) AnsiConsole.MarkupLine("[dim]Git initialized[/]");

		if (settings.LinkToUnity) // Link to Unity project if requested
		{
			if (UnityLinkLogic.TryFindUnityProject(fullPath, out var unityPath))
			{
				if (UnityLinkLogic.TryLinkToUnityProject(unityPath, fullPath, package.PackageName))
				{
					AnsiConsole.MarkupLine($"[green]Linked:[/] Added to Unity project at {unityPath}");
				}
				else
				{
					AnsiConsole.MarkupLine("[yellow]Warning:[/] Failed to link to Unity project");
				}
			}
			else
			{
				AnsiConsole.MarkupLine("[yellow]Warning:[/] No Unity project found in parent directories");
			}
		}

		return 0;
	}

	private void ListTemplates()
	{
		var templatesDir = GetAppDataPath();
		var templatesPath = Path.Combine(templatesDir, "PackageSmith", "Templates");

		if (!Directory.Exists(templatesPath))
		{
			AnsiConsole.MarkupLine("  [dim]No templates found[/]");
			return;
		}

		foreach (var t in Directory.GetDirectories(templatesPath))
		{
			var name = Path.GetFileName(t);
			AnsiConsole.MarkupLine($"  • [cyan]{name}[/]");
		}
	}

	private static string GetAppDataPath()
	{
		if (OperatingSystem.IsWindows())
			return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData));
		if (OperatingSystem.IsMacOS())
			return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Library", "Application Support");
		return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".local", "share");
	}

	private static string GetDisplayNameFromPackage(string packageName)
	{
		var parts = packageName.Split('.');
		if (parts.Length >= 3)
		{
			var companyName = ToPascalCase(parts[1]);
			var productName = ToPascalCase(parts[^1]);
			return $"{companyName} {productName}";
		}
		return ToPascalCase(packageName);
	}

	private static string ToPascalCase(string input)
	{
		if (string.IsNullOrEmpty(input)) return input;
		var parts = input.Split('-', '_');
		var result = new System.Text.StringBuilder();
		foreach (var part in parts)
		{
			if (string.IsNullOrEmpty(part)) continue;
			result.Append(char.ToUpperInvariant(part[0]));
			if (part.Length > 1)
				result.Append(part.Substring(1).ToLowerInvariant());
		}
		return result.Length > 0 ? result.ToString() : input;
	}
}
