using System;
using Spectre.Console;
using PackageSmith.App.Bridges;
using PackageSmith.Data.State;
using PackageSmith.Data.Types;
using PackageSmith.Core.Logic;

namespace PackageSmith.App.UX;

public static class StateMachine
{
	public static int Run()
	{
		ShowBanner();
		NewPackageFlow();
		return 0;
	}

	private static void ShowBanner()
	{
		AnsiConsole.MarkupLine("[bold cyan]◆[/] [bold white]PackageSmith[/]\n");
	}

	private static void NewPackageFlow()
	{
		AnsiConsole.MarkupLine("[bold white]New Package[/]\n");

		var name = AnsiConsole.Ask<string>("[dim]Package name[/] (e.g. [cyan]com.studio.tool[/]):");
		var parts = name.Split('.');
		var display = AnsiConsole.Ask<string>("[dim]Display name[/]:", parts.Length > 0 ? parts[^1] : name);

		var template = AnsiConsole.Prompt(
			new SelectionPrompt<TemplateType>()
				.AddChoices(TemplateType.None, TemplateType.MonoBehaviour, TemplateType.EcsFull));

		GitLogic.TryGetGitConfig(out var gitUser, out var _);
		var defaultCompany = !string.IsNullOrEmpty(gitUser) ? gitUser : "YourCompany";

		var package = new PackageState
		{
			PackageName = name,
			DisplayName = display,
			Description = "Generated by PackageSmith",
			OutputPath = Environment.CurrentDirectory,
			CompanyName = defaultCompany,
			SelectedTemplate = template,
			EcsPreset = new EcsPresetState { EnableEntities = template == TemplateType.EcsFull },
			SelectedModules = PackageModuleType.Runtime | PackageModuleType.Editor
		};

		var bridge = new PackageBridge();
		if (bridge.TryCreate(in package))
		{
			PackageLogic.CombinePath(package.OutputPath, package.PackageName, out var fullPath);
			GitLogic.TryInitGit(fullPath, out var gitInit);

			AnsiConsole.MarkupLine(gitInit
				? "[green]git initialized[/]"
				: "[dim]git init skipped[/]");

			AnsiConsole.MarkupLine("\n[bold green]Done[/]. Press Enter.");
			Console.ReadLine();
		}
	}
}
